# -*- coding: utf-8 -*-
"""transformada de Fourier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBMrTqjMN29Qwr3c8PgtyxCGgvAyzCAe
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_fourier_analysis():
    fs = 1000  # Frecuencia de muestreo
    t = np.linspace(-1, 1, fs, endpoint=False)

    fig, axs = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('Simulación de Señales y Transformada de Fourier', fontsize=16)

    # 1. Señal Senoidal (Frecuencia)
    f0 = 10
    x1 = np.sin(2 * np.pi * f0 * t)
    X1 = np.abs(np.fft.fftshift(np.fft.fft(x1))) / fs
    freqs = np.fft.fftshift(np.fft.fftfreq(fs, 1/fs))

    axs[0, 0].plot(freqs, X1)
    axs[0, 0].set_title('Espectro de Magnitud: Señal Senoidal (10 Hz)')
    axs[0, 0].set_xlim(-20, 20)
    axs[0, 0].grid()

    # 2. Pulso Rectangular (Función Sinc)
    rect = np.where(np.abs(t) < 0.1, 1, 0)
    RECT = np.abs(np.fft.fftshift(np.fft.fft(rect))) / fs

    axs[0, 1].plot(freqs, RECT)
    axs[0, 1].set_title('Espectro de Pulso Rectangular (Función Sinc)')
    axs[0, 1].set_xlim(-50, 50)
    axs[0, 1].grid()

    # 3. Propiedad de Escalamiento (Pulso más angosto = Espectro más ancho)
    rect_narrow = np.where(np.abs(t) < 0.05, 1, 0)
    RECT_N = np.abs(np.fft.fftshift(np.fft.fft(rect_narrow))) / fs

    axs[1, 0].plot(freqs, RECT, label='Ancho 0.2')
    axs[1, 0].plot(freqs, RECT_N, label='Ancho 0.1 (Escalamiento)', linestyle='--')
    axs[1, 0].set_title('Propiedad de Escalamiento')
    axs[1, 0].legend()
    axs[1, 0].set_xlim(-100, 100)
    axs[1, 0].grid()

    # 4. Fase de la Señal (Desplazamiento)
    x_shift = np.sin(2 * np.pi * f0 * (t - 0.05))
    X_fase = np.angle(np.fft.fftshift(np.fft.fft(x_shift)))

    axs[1, 1].plot(freqs, X_fase)
    axs[1, 1].set_title('Espectro de Fase (Desplazamiento en Tiempo)')
    axs[1, 1].set_xlim(-20, 20)
    axs[1, 1].grid()

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_fourier_analysis()